### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by habibulilalbaab** [fdciabdul/BCA-Mutasi-Scraper#35]
`error  RequestError: Error: unable to verify the first certificate
    at new RequestError (/root/node_modules/request-promise-core/lib/errors.js:14:15)
    at plumbing.callback (/root/node_modules/request-promise-core/lib/plumbing.js:87:29)
    at Request.RP$callback [as _callback] (/root/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at self.callback (/root/node_modules/request/request.js:185:22)
    at Request.emit (node:events:512:28)
    at Request.onRequestError (/root/node_modules/request/request.js:877:8)
    at ClientRequest.emit (node:events:512:28)
    at TLSSocket.socketErrorListener (node:_http_client:496:9)
    at TLSSocket.emit (node:events:512:28)
    at emitErrorNT (node:internal/streams/destroy:151:8) {
  cause: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
      at TLSSocket.emit (node:events:512:28)
      at TLSSocket._finishInit (node:_tls_wrap:959:8)
      at ssl.onhandshakedone (node:_tls_wrap:743:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  },
  error: Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (node:_tls_wrap:1540:34)
      at TLSSocket.emit (node:events:512:28)
      at TLSSocket._finishInit (node:_tls_wrap:959:8)
      at ssl.onhandshakedone (node:_tls_wrap:743:12) {
    code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE'
  },
  options: {
    headers: {
      'User-Agent': 'Mozilla/5.0 (Linux; U; Android 2.3.7; en-us; Nexus One Build/GRK39F) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 Mobile Safari/533.1',
      Referer: 'https://ibank.klikbca.com/authentication.do?value(actions)=menu'
    },
    jar: RequestJar { _jar: [CookieJar] },
    method: 'GET',
    uri: 'https://ibank.klikbca.com/authentication.do?value(actions)=logout',
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
  response: undefined
}`

**Comment by nusendra** [comment]
got this issues as well

**Comment by nusendra** [comment]
yup u right, seems BCA has updated their system so we cannot get the settlements or balance anymore.

**Comment by fdciabdul** [comment]
hi guys @nusendra @habibulilalbaab 

use this https://github.com/fdciabdul/mutasi-scraper instead , im not maintain this anymore

**Comment by nusendra** [comment]
Ok, then could u pleasea change this repo to archive instead? @fdciabdul

**Comment by fdciabdul** [comment]
@nusendra as you can see , the source repo isn't archive https://github.com/apriady/nodejs-bca-scraper

so if the source repo was update and got fixed , i will also update this repo
